/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Submission = IDL.Record({
  'name' : IDL.Text,
  'submittedAt' : Time,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'services' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
  'getAllSubmissionsByName' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
  'getAllSubmissionsByService' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Submission)],
      ['query'],
    ),
  'getSubmission' : IDL.Func([IDL.Text], [Submission], ['query']),
  'getSubmissionCount' : IDL.Func([], [IDL.Nat], ['query']),
  'removeForm' : IDL.Func([IDL.Text], [], []),
  'submitForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Submission = IDL.Record({
    'name' : IDL.Text,
    'submittedAt' : Time,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'services' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
    'getAllSubmissionsByName' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
    'getAllSubmissionsByService' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Submission)],
        ['query'],
      ),
    'getSubmission' : IDL.Func([IDL.Text], [Submission], ['query']),
    'getSubmissionCount' : IDL.Func([], [IDL.Nat], ['query']),
    'removeForm' : IDL.Func([IDL.Text], [], []),
    'submitForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };